apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  labels:
    app: postgres  
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      name: postgres
      labels:
        app: postgres
    spec:
      containers:      
      - image: postgres
        name: postgres
        ports:
        - name: db
          containerPort: 5432
        env:
            - name: POSTGRES_USER
              value: mimic_user
            - name: POSTGRES_PASSWORD
              value: mimic_passw0rd
---
apiVersion: v1
kind: Service
metadata:
  name: mimic-db-server
  labels:
    app: postgres
spec:
  type: ClusterIP  
  ports:
  - port: 5432
    targetPort: 5432
    name: db
    protocol: TCP
  selector:
    app: postgres
